# -*- coding: utf-8 -*-
"""MedGemma Minimal VQA Interface

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-V4aWNTJHlrgLsS6OIyFO64i0qCxYBI
"""

import gradio as gr
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
from PIL import Image
import os

MODEL_NAME = "google/medgemma-4b-it"
HF_TOKEN = os.getenv("HF_TOKEN", "")

processor = None
model = None

def initialize_model():
    global processor, model
    if processor is None or model is None:
        processor = AutoProcessor.from_pretrained(
            MODEL_NAME,
            token=HF_TOKEN,
            use_fast=True
        )
        model = AutoModelForImageTextToText.from_pretrained(
            MODEL_NAME,
            token=HF_TOKEN,
            torch_dtype=torch.bfloat16,
            device_map="auto"
        )
    return True

def generate_response(image, question):
    if not initialize_model():
        return "Error loading model"

    if image is None or not question.strip():
        return "Please provide both an image and a question"

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text", "text": question}
            ]
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt"
    ).to(model.device, dtype=torch.bfloat16)

    input_len = inputs["input_ids"].shape[-1]

    with torch.inference_mode():
        generation = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.3,
            do_sample=True
        )
        generation = generation[0][input_len:]

    return processor.decode(generation, skip_special_tokens=True)

with gr.Blocks() as demo:
    gr.Markdown("# MedGemma-4B-IT Medical VQA")
    gr.Markdown("Upload a medical image and ask a question about it")

    with gr.Row():
        with gr.Column():
            image_input = gr.Image(label="Medical Image", type="pil")
            text_input = gr.Textbox(
                label="Question",
                placeholder="What findings are present in this image?",
                lines=3
            )
            submit_btn = gr.Button("Submit", variant="primary")

        with gr.Column():
            output_text = gr.Textbox(
                label="Response",
                lines=10,
                interactive=False
            )

    submit_btn.click(
        fn=generate_response,
        inputs=[image_input, text_input],
        outputs=output_text
    )

    text_input.submit(
        fn=generate_response,
        inputs=[image_input, text_input],
        outputs=output_text
    )

demo.launch(share=True)