# -*- coding: utf-8 -*-
"""MedGemma Conversational Medical Assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHm8JtxIY0PCcRS1Np9PBW_yKTR2kmXq
"""

import gradio as gr
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
from PIL import Image
import os
from google.colab import userdata

api_key = userdata.get('HF_API_KEY')
os.environ['HF_API_KEY'] = api_key

MODEL_NAME = "google/medgemma-4b-it"

processor = None
model = None

def initialize_model():
    global processor, model
    if processor is None or model is None:
        try:
            print("Loading MedGemma-4B-IT model...")
            processor = AutoProcessor.from_pretrained(
                MODEL_NAME,
                token=api_key
            )
            model = AutoModelForImageTextToText.from_pretrained(
                MODEL_NAME,
                token=api_key,
                torch_dtype=torch.bfloat16,
                device_map="auto"
            )
            print("Model loaded successfully!")
        except Exception as e:
            print(f"Error loading model: {e}")
            return False
    return True

initialize_model()

def process_medical_case(image, text_input, conversation_history):
    if processor is None or model is None:
        if not initialize_model():
            return "Error: Model not loaded.", []

    is_initial = len(conversation_history) == 0

    # Build messages in the required format
    messages = []

    if is_initial:
        # System message
        messages.append({
            "role": "system",
            "content": [{"type": "text", "text": "You are an expert medical assistant."}]
        })

        # User message with image and/or text
        user_content = []
        if image is not None:
            user_content.append({"type": "image", "image": image})

        if text_input:
            prompt_text = f"""Analyze this medical case and provide an initial diagnosis.

Patient Information:
{text_input}

Please provide:
1. Initial observations
2. Potential diagnosis
3. Recommended next steps for further evaluation"""
        else:
            if image is None:
                return "Please provide either an image, text description, or both.", []
            prompt_text = """Analyze this medical image and provide an initial diagnosis.

Please examine the medical image and provide:
1. Initial observations
2. Potential diagnosis
3. Recommended next steps for further evaluation"""

        user_content.append({"type": "text", "text": prompt_text})
        messages.append({"role": "user", "content": user_content})
    else:
        # Rebuild conversation history
        messages.append({
            "role": "system",
            "content": [{"type": "text", "text": "You are an expert medical assistant."}]
        })

        for entry in conversation_history:
            if entry["role"] == "user":
                messages.append({
                    "role": "user",
                    "content": [{"type": "text", "text": entry["content"]}]
                })
            elif entry["role"] == "assistant":
                messages.append({
                    "role": "assistant",
                    "content": [{"type": "text", "text": entry["content"]}]
                })

        # Add current message
        user_content = []
        if image is not None:
            user_content.append({"type": "image", "image": image})
        user_content.append({"type": "text", "text": text_input})
        messages.append({"role": "user", "content": user_content})

    try:
        # Convert image to PIL if needed
        if image is not None:
            if isinstance(image, str):
                image = Image.open(image)
            elif not isinstance(image, Image.Image):
                image = Image.fromarray(image)

            # Update image in messages
            for msg in messages:
                if msg["role"] == "user":
                    for item in msg["content"]:
                        if item.get("type") == "image":
                            item["image"] = image

        # Apply chat template
        inputs = processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt"
        ).to(model.device, dtype=torch.bfloat16)

        input_len = inputs["input_ids"].shape[-1]

        with torch.inference_mode():
            generation = model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.7,
                do_sample=True,
                top_p=0.9
            )
            generation = generation[0][input_len:]

        response = processor.decode(generation, skip_special_tokens=True)

        # Update conversation history
        if is_initial:
            user_content_text = text_input if text_input else "Please analyze this medical case."
            conversation_history = [
                {"role": "user", "content": user_content_text},
                {"role": "assistant", "content": response}
            ]
        else:
            conversation_history.append({"role": "user", "content": text_input})
            conversation_history.append({"role": "assistant", "content": response})

        return response, conversation_history

    except Exception as e:
        error_msg = f"Error: {str(e)}"
        print(error_msg)
        return error_msg, conversation_history

def clear_conversation():
    return [], []

with gr.Blocks(title="MedGemma-4B-IT Medical Diagnosis Assistant") as demo:
    gr.Markdown("""
# MedGemma-4B-IT Medical Diagnosis Assistant

This application uses Google's MedGemma-4B-IT multimodal model for medical case analysis.

**Features:**
- Upload medical images (X-rays, scans, etc.)
- Provide text descriptions of symptoms or medical history
- Use both image and text together
- Get initial diagnosis and discuss further details

**Note:** This is a research tool and should not be used as a substitute for professional medical advice.
    """)

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                label="Medical Image (Optional)",
                type="pil",
                height=400
            )

            text_input = gr.Textbox(
                label="Patient Information / Symptoms / Follow-up Question",
                placeholder="Enter patient symptoms, medical history, or ask follow-up questions...",
                lines=5
            )

            submit_btn = gr.Button("Submit Case / Ask Question", variant="primary", size="lg")
            clear_btn = gr.Button("Clear Conversation", variant="secondary")

        with gr.Column(scale=1):
            output_text = gr.Textbox(
                label="Diagnosis / Response",
                lines=15,
                interactive=False
            )

            conversation_state = gr.State(value=[])

    submit_btn.click(
        fn=process_medical_case,
        inputs=[image_input, text_input, conversation_state],
        outputs=[output_text, conversation_state]
    )

    text_input.submit(
        fn=process_medical_case,
        inputs=[image_input, text_input, conversation_state],
        outputs=[output_text, conversation_state]
    )

    clear_btn.click(
        fn=clear_conversation,
        outputs=[conversation_state, output_text]
    )

    gr.Markdown("""
### Usage Instructions:
1. **Initial Diagnosis**: Upload an image and/or enter patient information, then click "Submit Case"
2. **Follow-up Questions**: After receiving the initial diagnosis, type your question in the text box and submit
3. **Clear Conversation**: Click "Clear Conversation" to start a new case

### Disclaimer:
This tool is for research and educational purposes only. Always consult qualified healthcare professionals for medical diagnosis and treatment.
    """)

if __name__ == "__main__":
    demo.launch(share=False)