# -*- coding: utf-8 -*-
"""MedGemma 1.5 Multimodal Chat with Conversation History

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVnGpQef5jjTXj-GCw3i_E-LGlDmLXK7

# MedGemma 1.5 Multimodal Chat with Conversation History

This notebook implements a stateful medical chatbot using Google's MedGemma 1.5 4B model.

**Features:**
- Conversation history management (text + images)
- Memory-efficient image handling
- Automatic context window trimming
- Support for X-rays, CT scans, dermatology images, and more

**Important Note:** MedGemma is a research tool and not a substitute for professional medical advice.

token : <set via environment or prompt>

## 1. Installation & Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install -q torch transformers accelerate pillow huggingface_hub
# 
# import sys
# import transformers
# 
# print(f"Python version: {sys.version}")
# print(f"Transformers version: {transformers.__version__}")
# 
# assert transformers.__version__ >= "4.50.0", "Transformers >= 4.50.0 required for MedGemma 1.5"

"""## 2. Authentication

You must:
1. Accept the license at: https://huggingface.co/google/medgemma-1.5-4b-it
2. Create a token at: https://huggingface.co/settings/tokens
"""

from huggingface_hub import login

HF_TOKEN = input("Enter your HuggingFace token: ")
login(token=HF_TOKEN)

"""## 3. Load Model & Processor"""

import torch
from transformers import AutoProcessor, Gemma3ForConditionalGeneration

MODEL_ID = "google/medgemma-1.5-4b-it"

print(f"Loading {MODEL_ID}...")

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    token=HF_TOKEN
)

model = Gemma3ForConditionalGeneration.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    token=HF_TOKEN
).eval()

print(f"Model loaded on: {model.device}")
print(f"Model dtype: {model.dtype}")

"""## 4. Medical Chat Session Class"""

from PIL import Image
import requests
from io import BytesIO
from typing import List, Dict, Union, Optional
import gc

class MedGemmaChatSession:
    def __init__(
        self,
        model,
        processor,
        max_turns_with_images: int = 3,
        max_new_tokens: int = 512,
        temperature: float = 0.7,
        system_prompt: Optional[str] = None
    ):
        self.model = model
        self.processor = processor
        self.max_turns_with_images = max_turns_with_images
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature

        self.chat_history: List[Dict] = []
        self.image_count = 0

        if system_prompt is None:
            system_prompt = (
                "You are a helpful medical AI assistant. You analyze medical images and text. "
                "Always remind users to consult qualified healthcare professionals for medical decisions."
            )

        self.chat_history.append({
            "role": "system",
            "content": [{"type": "text", "text": system_prompt}]
        })

    def _load_image(self, image_input: Union[str, Image.Image]) -> Image.Image:
        if isinstance(image_input, Image.Image):
            return image_input.convert("RGB")

        if image_input.startswith("http://") or image_input.startswith("https://"):
            response = requests.get(image_input)
            response.raise_for_status()
            return Image.open(BytesIO(response.content)).convert("RGB")
        else:
            return Image.open(image_input).convert("RGB")

    def _manage_memory(self):

        image_turns = sum(
            1 for msg in self.chat_history
            if any(item["type"] == "image" for item in msg.get("content", []))
        )

        while image_turns > self.max_turns_with_images:
            for i in range(1, len(self.chat_history)):
                if any(item["type"] == "image" for item in self.chat_history[i].get("content", [])):
                    self.chat_history.pop(i)
                    image_turns -= 1
                    break

        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        gc.collect()

    def add_message(
        self,
        text: str,
        image: Optional[Union[str, Image.Image]] = None
    ) -> str:
        content = []

        if image is not None:
            try:
                pil_image = self._load_image(image)
                content.append({"type": "image", "image": pil_image})
                self.image_count += 1
            except Exception as e:
                print(f"Warning: Failed to load image: {e}")

        if text:
            content.append({"type": "text", "text": text})

        if not content:
            raise ValueError("Must provide either text or image")

        self.chat_history.append({
            "role": "user",
            "content": content
        })

        try:
            inputs = self.processor.apply_chat_template(
                self.chat_history,
                add_generation_prompt=True,
                tokenize=True,
                return_dict=True,
                return_tensors="pt"
            ).to(self.model.device, dtype=torch.bfloat16)

            input_len = inputs["input_ids"].shape[-1]

            with torch.inference_mode():
                generation = self.model.generate(
                    **inputs,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=True,
                    temperature=self.temperature,
                    pad_token_id=self.processor.tokenizer.pad_token_id
                )

            response_text = self.processor.decode(
                generation[0][input_len:],
                skip_special_tokens=True
            )

            self.chat_history.append({
                "role": "assistant",
                "content": [{"type": "text", "text": response_text}]
            })

            self._manage_memory()

            return response_text

        except Exception as e:
            print(f"Error during generation: {e}")
            self.chat_history.pop()
            raise

    def get_history_summary(self) -> str:
        total_turns = len([m for m in self.chat_history if m["role"] == "user"])
        images_in_history = sum(
            sum(1 for item in msg.get("content", []) if item["type"] == "image")
            for msg in self.chat_history
        )

        return (
            f"Session stats:\n"
            f"- Total turns: {total_turns}\n"
            f"- Images in history: {images_in_history}\n"
            f"- Total images uploaded: {self.image_count}"
        )

    def clear_history(self, keep_system_prompt: bool = True):
        if keep_system_prompt:
            self.chat_history = self.chat_history[:1]
        else:
            self.chat_history = []
        self.image_count = 0
        self._manage_memory()

print("MedGemmaChatSession class loaded successfully!")

"""## 5. Initialize Chat Session"""

session = MedGemmaChatSession(
    model=model,
    processor=processor,
    max_turns_with_images=3,
    max_new_tokens=512,
    temperature=0.7
)

print("Chat session initialized!")

"""## 6. Example Usage

### Text-only Conversation
"""

response = session.add_message(
    text="What are the main symptoms of pneumonia?"
)
print(f"MedGemma: {response}")

"""### Image Analysis (Example with URL)"""

# Mount GDrive
from google.colab import drive
drive.mount('/content/drive')

# Verify the file exists
!ls -lh /content/drive/MyDrive/CXR/Test.jpg

from PIL import Image
import matplotlib.pyplot as plt

# Preview the image
img = Image.open("/content/drive/MyDrive/CXR/Test.jpg")
plt.figure(figsize=(10, 10))
plt.imshow(img, cmap='gray')
plt.axis('off')
plt.title("Chest X-ray")
plt.show()

# # Then analyze it
# response = session.add_message(
#     text="Please analyze this chest X-ray for any abnormalities.",
#     image="/content/drive/MyDrive/CXR/Test.jpg"
# )
# print(f"MedGemma: {response}")

# Clear and reinitialize the session
session = MedGemmaChatSession(
    model=model,
    processor=processor,
    max_turns_with_images=3,
    max_new_tokens=512,
    temperature=0.7
)

# Now try your image
response = session.add_message(
    text="Please analyze this chest X-ray for any abnormalities.",
    image="/content/drive/MyDrive/CXR/Test.jpg"
)
print(f"MedGemma: {response}")

"""### Upload Local Image"""

# from google.colab import files

# uploaded = files.upload()

# for filename in uploaded.keys():
#     response = session.add_message(
#         text="What do you see in this medical image?",
#         image=filename
#     )
#     print(f"MedGemma: {response}")

"""### Follow-up Questions (Testing History)"""

response = session.add_message(
    text="Based on the previous X-ray, what additional tests would you recommend?"
)
print(f"MedGemma: {response}")

"""## 7. Interactive Chat Loop"""

def interactive_chat():
    print("MedGemma Interactive Chat")
    print("Commands:")
    print("  'upload' - Upload an image")
    print("  'stats' - Show session statistics")
    print("  'clear' - Clear chat history")
    print("  'quit' - Exit\n")

    while True:
        user_input = input("You: ").strip()

        if user_input.lower() in ['quit', 'exit']:
            print("Session ended.")
            break

        if user_input.lower() == 'upload':
            uploaded = files.upload()
            if uploaded:
                filename = list(uploaded.keys())[0]
                caption = input("Enter description (or press Enter): ").strip()
                if not caption:
                    caption = "Please analyze this medical image."

                try:
                    response = session.add_message(text=caption, image=filename)
                    print(f"MedGemma: {response}\n")
                except Exception as e:
                    print(f"Error: {e}\n")
            continue

        if user_input.lower() == 'stats':
            print(session.get_history_summary() + "\n")
            continue

        if user_input.lower() == 'clear':
            session.clear_history()
            print("History cleared.\n")
            continue

        if not user_input:
            continue

        try:
            response = session.add_message(text=user_input)
            print(f"MedGemma: {response}\n")
        except Exception as e:
            print(f"Error: {e}\n")

interactive_chat()

"""## 8. Session Management"""

print(session.get_history_summary())

session.clear_history()
print("History cleared")

"""## 9. Advanced: Save/Load Chat History"""

import json
import base64
from io import BytesIO

def save_session(session, filename="chat_history.json"):
    history_serializable = []

    for msg in session.chat_history:
        new_msg = {"role": msg["role"], "content": []}

        for item in msg["content"]:
            if item["type"] == "text":
                new_msg["content"].append(item)
            elif item["type"] == "image":
                buffered = BytesIO()
                item["image"].save(buffered, format="PNG")
                img_str = base64.b64encode(buffered.getvalue()).decode()
                new_msg["content"].append({
                    "type": "image_base64",
                    "data": img_str
                })

        history_serializable.append(new_msg)

    with open(filename, "w") as f:
        json.dump(history_serializable, f)

    print(f"Session saved to {filename}")

def load_session(session, filename="chat_history.json"):
    with open(filename, "r") as f:
        history_serializable = json.load(f)

    session.chat_history = []

    for msg in history_serializable:
        new_msg = {"role": msg["role"], "content": []}

        for item in msg["content"]:
            if item["type"] == "text":
                new_msg["content"].append(item)
            elif item["type"] == "image_base64":
                img_data = base64.b64decode(item["data"])
                img = Image.open(BytesIO(img_data))
                new_msg["content"].append({
                    "type": "image",
                    "image": img
                })

        session.chat_history.append(new_msg)

    print(f"Session loaded from {filename}")

print("Save/Load functions defined")

"""## 10. Troubleshooting

### Check GPU Memory
"""

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory allocated: {torch.cuda.memory_allocated(0) / 1e9:.2f} GB")
    print(f"Memory reserved: {torch.cuda.memory_reserved(0) / 1e9:.2f} GB")
else:
    print("No GPU available")

"""### Clear GPU Cache"""

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    gc.collect()
    print("GPU cache cleared")

"""## Important Notes

1. **Not Clinical Grade**: MedGemma is for research and development purposes only
2. **Multi-turn Limitation**: The model was not specifically optimized for multi-turn conversations
3. **Memory Management**: Images are automatically pruned after 3 turns to prevent OOM errors
4. **Validation Required**: Always validate outputs for your specific use case
5. **Context Window**: 128K tokens max, but practical limit is lower with images

## Citation

```
@article{sellergren2025medgemma,
  title={MedGemma Technical Report},
  author={Sellergren, Andrew and others},
  journal={arXiv preprint arXiv:2507.05201},
  year={2025}
}
```
"""