# -*- coding: utf-8 -*-
"""MedGemma Clinical Assistant (Evaluation-Disabled)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5hUu1iT_FsV8rrTeQ1E289UmZ-kIjYV
"""

import gradio as gr
import torch
from transformers import AutoProcessor, AutoModelForImageTextToText
from PIL import Image
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
import re
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import os

api_key = os.getenv("HF_TOKEN", "")
MODEL_NAME = "google/medgemma-4b-it"

processor = None
model = None
semantic_model = None

ANSWER_SYNONYMS = {
    "not seen here": ["not visible", "absent", "cannot be seen", "not present", "not shown", "not observed"],
    "not visible": ["not seen", "absent", "cannot be seen", "not present", "not shown"],
    "yes": ["present", "visible", "there is", "affirmative", "positive", "confirmed"],
    "no": ["absent", "not present", "none", "negative", "not visible", "not seen"],
    "left": ["left side", "on the left", "leftward"],
    "right": ["right side", "on the right", "rightward"],
    "smaller": ["reduced", "decreased", "diminished"],
    "larger": ["increased", "enlarged", "bigger", "expanded"]
}

def initialize_model():
    global processor, model, semantic_model
    if processor is None or model is None:
        try:
            print("Loading MedGemma-4B-IT model...")
            processor = AutoProcessor.from_pretrained(MODEL_NAME, token=api_key, use_fast=True)
            model = AutoModelForImageTextToText.from_pretrained(
                MODEL_NAME,
                token=api_key,
                dtype=torch.bfloat16,
                device_map="auto"
            )
            print("Model loaded successfully!")
        except Exception as e:
            print(f"Error loading model: {e}")
            return False

    # Commented out semantic model loading since evaluation is disabled
    # if semantic_model is None:
    #     try:
    #         print("Loading semantic similarity model...")
    #         semantic_model = SentenceTransformer('all-MiniLM-L6-v2')
    #         print("Semantic model loaded!")
    #     except Exception as e:
    #         print(f"Error loading semantic model: {e}")
    #         return False

    return True

initialize_model()

# All evaluation-related functions commented out
"""
def check_synonyms(prediction, ground_truth):
    pred_lower = prediction.lower().strip()
    gt_lower = ground_truth.lower().strip()

    if pred_lower == gt_lower:
        return True, "exact"

    if gt_lower in ANSWER_SYNONYMS:
        for synonym in ANSWER_SYNONYMS[gt_lower]:
            if synonym in pred_lower or pred_lower in synonym:
                return True, f"synonym: '{synonym}'"

    if pred_lower in ANSWER_SYNONYMS:
        for synonym in ANSWER_SYNONYMS[pred_lower]:
            if gt_lower in synonym or synonym in gt_lower:
                return True, f"synonym: '{synonym}'"

    return False, None

def semantic_similarity_score(text1, text2):
    if semantic_model is None:
        return 0.0

    embeddings = semantic_model.encode([text1, text2])
    similarity = cosine_similarity([embeddings[0]], [embeddings[1]])[0][0]
    return similarity

def extract_answer(text, ground_truth):
    text_lower = text.lower()
    gt_lower = ground_truth.lower()

    if gt_lower in ["yes", "no"]:
        yes_patterns = [r'\byes\b', r'\bthere is\b', r'\bpresent\b', r'\bvisible\b', r'\baffected\b', r'\bconfirmed\b']
        no_patterns = [r'\bno\b', r'\bnot\b', r'\babsent\b', r'\bnone\b', r'\bno evidence\b', r'\bno obvious\b', r'\bnot visible\b']

        yes_count = sum(1 for p in yes_patterns if re.search(p, text_lower))
        no_count = sum(1 for p in no_patterns if re.search(p, text_lower))

        if yes_count > no_count:
            return "yes"
        elif no_count > yes_count:
            return "no"

    comparatives = ["smaller", "larger", "left", "right", "reduced", "increased", "enlarged"]
    for comp in comparatives:
        if comp in text_lower:
            return comp

    visibility_terms = ["not visible", "not seen", "cannot be seen", "not present", "not shown"]
    for term in visibility_terms:
        if term in text_lower:
            return "not visible"

    if gt_lower in text_lower:
        return ground_truth

    first_sentence = text.split('.')[0].strip()
    return first_sentence

def normalize_answer(text):
    return text.lower().strip().replace(".", "").replace(",", "").replace("the ", "")

def is_answer_correct_detailed(prediction, ground_truth):
    pred_normalized = normalize_answer(prediction)
    gt_normalized = normalize_answer(ground_truth)

    if pred_normalized == gt_normalized:
        return True, "Exact Match", f"Normalized answers match exactly"

    matched, synonym_detail = check_synonyms(prediction, ground_truth)
    if matched:
        return True, "Synonym Match", f"Matched via {synonym_detail}"

    similarity = semantic_similarity_score(prediction, ground_truth)
    if similarity > 0.85:
        return True, "Semantic Match", f"Semantic similarity: {similarity:.3f} (threshold: 0.85)"

    return False, "No Match", f"Best similarity: {similarity:.3f} (below threshold 0.85)"

def generate_response(image, question):
    prompt = f"{question}\n\nProvide a concise answer (one word or short phrase preferred)."

    messages = [
        {"role": "system", "content": [{"type": "text", "text": "You are an expert medical assistant. Provide concise, direct answers."}]},
        {"role": "user", "content": [
            {"type": "image", "image": image},
            {"type": "text", "text": prompt}
        ]}
    ]

    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt"
    ).to(model.device, dtype=torch.bfloat16)

    input_len = inputs["input_ids"].shape[-1]

    with torch.inference_mode():
        generation = model.generate(
            **inputs,
            max_new_tokens=256,
            temperature=0.1,
            do_sample=False
        )
        generation = generation[0][input_len:]

    return processor.decode(generation, skip_special_tokens=True)

def is_chest_xray_question(question):
    chest_keywords = [
        'lung', 'chest', 'heart', 'cardiac', 'thorax', 'rib', 'pleural',
        'pneumonia', 'effusion', 'cardiomegaly', 'consolidation', 'airspace',
        'aortic', 'mediastinum', 'clavicle', 'bronchus', 'diaphragm'
    ]

    question_lower = question.lower()
    return any(keyword in question_lower for keyword in chest_keywords)

def create_detailed_html_results(detailed_results):
    html = ""
    # Full HTML generation code commented out
    return html

def pil_to_base64(img):
    import io
    import base64

    buffered = io.BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode()
    return f"data:image/png;base64,{img_str}"

def evaluate_on_dataset(dataset_name, num_samples, filter_chest_xray, progress=gr.Progress()):
    return "Evaluation disabled", None, None, ""
"""

def process_medical_case(image, text_input, conversation_history):
    if processor is None or model is None:
        if not initialize_model():
            return "Error: Model not loaded.", []

    is_initial = len(conversation_history) == 0
    messages = []

    if is_initial:
        messages.append({
            "role": "system",
            "content": [{"type": "text", "text": "You are an expert medical assistant."}]
        })

        user_content = []
        if image is not None:
            user_content.append({"type": "image", "image": image})

        if text_input:
            prompt_text = f"""Analyze this medical case and provide an initial diagnosis.

Patient Information:
{text_input}

Please provide:
1. Initial observations
2. Potential diagnosis
3. Recommended next steps for further evaluation"""
        else:
            if image is None:
                return "Please provide either an image, text description, or both.", []
            prompt_text = """Analyze this medical image and provide an initial diagnosis.

Please examine the medical image and provide:
1. Initial observations
2. Potential diagnosis
3. Recommended next steps for further evaluation"""

        user_content.append({"type": "text", "text": prompt_text})
        messages.append({"role": "user", "content": user_content})
    else:
        messages.append({
            "role": "system",
            "content": [{"type": "text", "text": "You are an expert medical assistant."}]
        })

        for entry in conversation_history:
            if entry["role"] == "user":
                messages.append({
                    "role": "user",
                    "content": [{"type": "text", "text": entry["content"]}]
                })
            elif entry["role"] == "assistant":
                messages.append({
                    "role": "assistant",
                    "content": [{"type": "text", "text": entry["content"]}]
                })

        user_content = []
        if image is not None:
            user_content.append({"type": "image", "image": image})
        user_content.append({"type": "text", "text": text_input})
        messages.append({"role": "user", "content": user_content})

    try:
        if image is not None:
            if isinstance(image, str):
                image = Image.open(image)
            elif not isinstance(image, Image.Image):
                image = Image.fromarray(image)

            for msg in messages:
                if msg["role"] == "user":
                    for item in msg["content"]:
                        if item.get("type") == "image":
                            item["image"] = image

        inputs = processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt"
        ).to(model.device, dtype=torch.bfloat16)

        input_len = inputs["input_ids"].shape[-1]

        with torch.inference_mode():
            generation = model.generate(
                **inputs,
                max_new_tokens=512,
                temperature=0.7,
                do_sample=True,
                top_p=0.9
            )
            generation = generation[0][input_len:]

        response = processor.decode(generation, skip_special_tokens=True)

        if is_initial:
            user_content_text = text_input if text_input else "Please analyze this medical case."
            conversation_history = [
                {"role": "user", "content": user_content_text},
                {"role": "assistant", "content": response}
            ]
        else:
            conversation_history.append({"role": "user", "content": text_input})
            conversation_history.append({"role": "assistant", "content": response})

        return response, conversation_history

    except Exception as e:
        error_msg = f"Error: {str(e)}"
        print(error_msg)
        return error_msg, conversation_history

def clear_conversation():
    return [], []

with gr.Blocks(title="MedGemma-4B-IT Medical Assistant", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
# 🏥 MedGemma-4B-IT Medical Assistant

Interactive medical diagnosis tool for research purposes.

⚠️ **Research tool only** - Not for clinical use.
    """)

    # Only Medical Diagnosis tab is active
    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                label="Medical Image",
                type="pil",
                height=400
            )

            text_input = gr.Textbox(
                label="Patient Information / Question",
                placeholder="Enter symptoms, history, or questions...",
                lines=5
            )

            with gr.Row():
                submit_btn = gr.Button("Submit", variant="primary", size="lg")
                clear_btn = gr.Button("Clear", variant="secondary")

        with gr.Column(scale=1):
            output_text = gr.Textbox(
                label="Response",
                lines=20,
                interactive=False
            )
            conversation_state = gr.State(value=[])

    submit_btn.click(
        fn=process_medical_case,
        inputs=[image_input, text_input, conversation_state],
        outputs=[output_text, conversation_state]
    )

    text_input.submit(
        fn=process_medical_case,
        inputs=[image_input, text_input, conversation_state],
        outputs=[output_text, conversation_state]
    )

    clear_btn.click(
        fn=clear_conversation,
        outputs=[conversation_state, output_text]
    )

    # EVALUATION TAB COMMENTED OUT
    """
    with gr.Tab("📊 Model Evaluation"):
        gr.Markdown('''
### 🎯 Comprehensive Evaluation with Detailed Analysis

Test MedGemma and see **exactly why** each answer was marked correct or incorrect.
        ''')

        with gr.Row():
            with gr.Column(scale=1):
                dataset_dropdown = gr.Dropdown(
                    choices=["VQA-RAD", "SLAKE", "PathVQA"],
                    value="VQA-RAD",
                    label="Dataset"
                )

                filter_checkbox = gr.Checkbox(
                    label="🔍 Filter for Chest X-rays Only (VQA-RAD)",
                    value=True,
                    info="Recommended for better accuracy"
                )

                num_samples_slider = gr.Slider(
                    minimum=5,
                    maximum=50,
                    value=15,
                    step=5,
                    label="Samples to Evaluate"
                )

                eval_btn = gr.Button("🚀 Run Evaluation", variant="primary", size="lg")

            with gr.Column(scale=1):
                eval_summary = gr.Textbox(
                    label="Evaluation Summary",
                    lines=12,
                    interactive=False
                )

        eval_plot = gr.Plot(label="📈 Results Visualization")

        eval_results = gr.Dataframe(
            label="Quick Results Overview",
            max_height=400
        )

        gr.Markdown("### 🔍 Detailed Analysis - Every Sample")
        gr.Markdown("Scroll through each sample to see the full image, question, ground truth, model response, and matching logic.")

        detailed_view = gr.HTML(label="Detailed Results")

        eval_btn.click(
            fn=evaluate_on_dataset,
            inputs=[dataset_dropdown, num_samples_slider, filter_checkbox],
            outputs=[eval_summary, eval_results, eval_plot, detailed_view]
        )

        gr.Markdown('''
#### 📖 Understanding the Detailed View:
- **Green Header**: Correct prediction ✓
- **Red Header**: Incorrect prediction ✗
- **Match Types**:
  - **Exact Match**: Normalized text matches perfectly
  - **Synonym Match**: Medical terms that mean the same thing
  - **Semantic Match**: AI-determined meaning similarity >0.85
  - **No Match**: Answer doesn't match any criteria
        ''')
    """

if __name__ == "__main__":
    demo.launch(share=False)